In [1]:
import pandas as pd

In [4]:
df=pd.read_csv('/content/netflix_titles.csv')

In [5]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [6]:
df.shape

(8154, 12)

In [7]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2518
cast             747
country          803
date_added         9
release_year       0
rating             4
duration           4
listed_in          1
description        1
dtype: int64

In [8]:
missing_percent = (df.isnull().sum() / len(df)) * 100
missing_percent

show_id          0.000000
type             0.000000
title            0.000000
director        30.880549
cast             9.161148
country          9.847927
date_added       0.110375
release_year     0.000000
rating           0.049056
duration         0.049056
listed_in        0.012264
description      0.012264
dtype: float64

In [9]:
df.fillna("Unknown", inplace=True)

In [10]:
df.isnull().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [13]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(' ', '_')
)

In [14]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [15]:
df.dtypes

show_id         object
type            object
title           object
director        object
cast            object
country         object
date_added      object
release_year     int64
rating          object
duration        object
listed_in       object
description     object
dtype: object

In [16]:
df['date_added'].head(10)

0    September 25, 2021
1    September 24, 2021
2    September 24, 2021
3    September 24, 2021
4    September 24, 2021
5    September 24, 2021
6    September 24, 2021
7    September 24, 2021
8    September 24, 2021
9    September 24, 2021
Name: date_added, dtype: object

In [17]:
df['date_added'] = pd.to_datetime(
    df['date_added'],
    errors='coerce'
)

In [18]:
df['date_added'].dtype

dtype('<M8[ns]')

In [19]:
df['date_added'].isnull().sum()

np.int64(77)

In [20]:
df['date_added'].dtype

dtype('<M8[ns]')

In [21]:
df['date_added'] = df['date_added'].dt.strftime('%d-%m-%y')

In [22]:
df['date_added'].head(10)

0    25-09-21
1    24-09-21
2    24-09-21
3    24-09-21
4    24-09-21
5    24-09-21
6    24-09-21
7    24-09-21
8    24-09-21
9    24-09-21
Name: date_added, dtype: object

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8154 entries, 0 to 8153
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8154 non-null   object
 1   type          8154 non-null   object
 2   title         8154 non-null   object
 3   director      8154 non-null   object
 4   cast          8154 non-null   object
 5   country       8154 non-null   object
 6   date_added    8077 non-null   object
 7   release_year  8154 non-null   int64
 8   rating        8154 non-null   object
 9   duration      8154 non-null   object
 10  listed_in     8154 non-null   object
 11  description   8154 non-null   object
dtypes: int64(1), object(11)
memory usage: 764.6+ KB

In [24]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Unknown,United States,25-09-21,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,24-09-21,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown,24-09-21,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,Unknown,Unknown,Unknown,24-09-21,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,24-09-21,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [25]:
df.isnull().sum()

show_id          0
type             0
title            0
director         0
cast             0
country          0
date_added      77
release_year     0
rating           0
duration         0
listed_in        0
description      0
dtype: int64

In [27]:
df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')

/tmp/ipykernel_1125/437285913.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')

In [28]:
df['date_added'] = pd.to_datetime(
    df['date_added'],
    format='%B %d, %Y',
    errors='coerce'
)

In [29]:
df['date_added'].head()

0   2021-09-25
1   2021-09-24
2   2021-09-24
3   2021-09-24
4   2021-09-24
Name: date_added, dtype: datetime64[ns]

In [30]:
df.duplicated().sum()

np.int64(0)

In [32]:
# 77 values remain missing because the original dataset does not contain valid date information for these records.
# We keep them as missing instead of adding incorrect or made-up dates.
df.isnull().sum()

show_id          0
type             0
title            0
director         0
cast             0
country          0
date_added      77
release_year     0
rating           0
duration         0
listed_in        0
description      0
dtype: int64

In [33]:
# Save the cleaned dataset
df.to_csv('cleaned_netflix_data.csv', index=False)